baseurl       = "https://beam-fosdem.dev"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title         = "BEAM FOSDEM"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "Erlang, Elixir, Gleam and Friends at FOSDEM'24"
  logo = "img/fosdem_circle.png"
  favicon = "img/fosdem.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  table = false

[Author]
  # name = ""
  email = "erlang-devroom-manager@fosdem.org"
  github = "beam-fosdem/beam-fosdem.github.io"

[[menu.main]]
    name = "Call for Talks"
    url = "call-for-talks"
    weight = 1

#[[menu.main]]
#    name = "Schedule"
#    url = "schedule"
#    weight = 1

#[[menu.main]]
#    name = "Meetup"
#    url = "meetup"
#    weight = 2

[[menu.main]]
    name = "About Us"
    url = "about-us"
    weight = 3

[[menu.main]]
    identifier = "previous-editions"
    name = "Previous Editions"
    weight = 4

[[menu.main]]
    parent = "previous-editions"
    name = "2020"
    url = "2020-edition"
    weight = 5

[markup.goldmark.renderer]
    unsafe= true
